import { IoArrowForward } from "react-icons/io5";
import CreateUserGroup from "../Components/UserGroupCreate/CreateUser";
import CompanyMaintenanceScreen from "../Views/CompanyMaintenanceScreen/CompanyMaintenanceScreen";

import BlockNumberDevice from "../Views/DeviceManagement/BlockNumberDevice";

import GroupRights from "../Views/GroupsRights/GroupRights";
import PayrollEnquirey from "../Views/PayrollEnquirey/PayrollEnquiry";
import IdTypeRouting from "../Views/IdTypeRouting/IdTypeRouting";
import IdTypeCreate from "../Views/IdTypeRoutingCreate/IdTypeCreate";
import IdTypeEdit from "../Views/IdTypeRoutingEdit/IdTypeEdit";
import LockedBackOfficeUser from "../Views/LockedBackOfficeUser/LockedBackOfficeUser";
import LockedCustomer from "../Views/LockedCustomer/LockedCustomer";

import ReferenceData from "../Views/ReferenceData/ReferenceData";
import ReferenceDataCreate from "../Views/ReferenceDataCreate/ReferenceDataCreate";
import ReferenceDataEdit from "../Views/ReferenceDataEdit/ReferenceDataEdit";

import UserDetails from "../Views/User/UserDetails";
import UserGroups from "../Views/UserGroup/UserGroups";
import UserRights from "../Views/UserRight/UserRights";
import UserLoginRecords from "../Views/UserLoginRecords/UserLoginRecords";

import eKYCPendingCustomer from "../Views/eKYCPendingCustomer/eKYCPendingCustomer";
import KYCPendingCustomer from "../Views/KYCPendingCustomer/KYCPendingCustomer";
import TopUpAdd from "../Views/TopUpAdd/TopUpAdd";
import PrefundTransactionEnquiry from "../Views/PrefundTransactionEnquiry/PrefundTransactionEnquiry";
import AccountTransaction from "../Views/AccountTransaction/AccountTransaction";
import PreFundProcessing from "../Views/PreFundProcessing/PreFundProcessing";
import AmlPendingCustomers from "../Views/AmlPendingCustomers/AmlPendingCustomers";
import DeviceMobileHistory from "../Views/DeviceMobileHistory/DeviceMobileHistory";
import GlobalSettings from "../Views/GlobalSettings/GlobalSettings";
import CompanyPayrollAccountEnquiry from "../Views/CompanyPayrollAccountEnquiry/CompanyPayrollAccountEnquiry";
import LockedDeviceHistory from "../Views/LockedDeviceHistory/LockedDeviceHistory";
import GlobalSettingsDevice from "../Views/GlobalSettingsDevice/GlobalSettingsDevice";
import CompanyUserScreenList from "../Views/CompanyUserScreen/CompanyUserScreenList";
import RemitCountrySetup from "../Views/RemitCountrySetup/RemitCountrySetup";
import RemitBankSetup from "../Views/RemitBankSetup/RemitBankSetup";
import RemitBranchSetup from "../Views/RemitBranchSetup/RemitBranchSetup";
import RemitAgentTag from "../Views/RemitAgentTag/RemitAgentTag";
import PreOnBoarding from "../Views/PreOnBoading/PreOnBoarding";
import PreOnBoardingCustomer from "../Views/PreOnBoading/PreOnBoardingCustomer/PreOnBoardingCustomer";
import BranchDashboard from "../Views/BranchDashboard/BranchDashboard";
import AddBranch from "../Components/AddBranch/AddBranch";
import TerminalDashboard from "../Views/TerminalDashboard/TerminalDashboard";
import AgentGroup from "../Views/AgentGroup/AgentGroup";
import RemitBankForm from "../Views/RemitBankSetup/RemitBankForm";
import BankPaymentGatewayMapping from "../Views/BankPaymentGatewayMapping/BankPaymentGatewayMapping";
import NotificationMasterSetup from "../Views/NotificationMasterSetup/NotificationMasterSetup";
import NotificationMasterForm from "../Views/NotificationMasterSetup/NotificationMasterForm";
import NotificationChannelSetup from "../Views/NotificationChannelSetup/NotificationChannelSetup";
import NotificationChannelEdit from "../Views/NotificationChannelSetup/NotificationChannelEdit";
import RemitTransactionProcessing from "../Views/RemitTransactionProcessing/RemitTransactionProcessing";
import RemitTransactionEnquiry from "../Views/RemitTransactionEnquiry/RemitTransactionEnquiry";
import RemitEditOnBehalf from "../Views/RemitTransactionEnquiry/RemitEditOnBehalf";
import RemitTransactionStatus from "../Views/RemitTransactionStatus/RemitTransactionStatus";
import RemittanceFeesAndCharges from "../Views/RemittanceFeesAndCharges/RemittanceFeesAndCharges";
import BlockCardRequest from "../Views/BlockCardRequest/BlockCardRequest";
import AddBlockCardRequest from "../Components/AddBlockCardRequest/AddBlockCardRequest";
import ToggleSummary from "../Views/ToggleSummary/ToggleSummary";
import ParameterSummary from "../Views/ParameterSummary/ParameterSummary";
import CommonEditSummary from "../Components/EditSummary/CommonEditSummary";
import BlockCardRequestViewDetail from "../Components/BlockCardRequestViewDetail/BlockCardRequestViewDetail";
import AMLcompliance from "../Views/AMLcompliance/AMLcompliance";
import RemitTransactionLimit from "../Views/RemitTransactionLimit/RemitTransactionLimit";
import CardReplacement from "../Views/CardReplacement/CardReplacement";
import AddCardReplacement from "../Components/AddCardReplacement/AddCardReplacement";
import ViewCardReplacement from "../Components/ViewCardReplacement/ViewCardReplacement";
import CardUnblock from "../Views/CardUnblock/CardUnblock";
import CardUnblockView from "../Components/CradUnblockView/CardUnblockView";
import AddCardUnblock from "../Components/AddCardUnblock/AddCardUnblock";
import CardUpgrade from "../Views/CardUpgrade/CardUpgrade";
import AddETerminal from "../Components/AddETerminal/AddETerminal";
import RemittanceAddLimit from "../Views/RemitTransactionLimit/AddTransactionLimit";
import MobileTopUpSummary from "../Views/MobileTopUpSummary/MobileTopUpSummary";
import AmlEcddSetup from "../Views/AmlEcddSetup/AmlEcddSetup";
import AmlRiskScale from "../Views/AmlRiskScale/AmlRiskScale";
import AmlTransactionStatistics from "../Views/AmlTransactionStatistics/AmlTransactionStatistics";
import DocUploadRequest from "../Views/DocUploadRequest/DocUploadRequest";
import DocUploadRequestView from "../Components/DocUploadRequestAdd/DocUploadRequestView";
import DocUploadRequestAdd from "../Components/DocUploadRequestAdd/DocUploadRequestAdd";
import RemitRiskFactor from "../Views/RemitRiskFactor/RemitRiskFactor";
import RemitRiskFactorStatusConfiguration from "../Views/RemitRiskFactorStatusConfiguration/RemitRiskFactorStatusConfiguration";
import MobileTopupSummaryTable from "../Views/MobileTopUpSummary/MobileTopupSummaryTable";
import RemitRiskRating from "../Views/RemitRiskRating/RemitRiskRating";
import RemitHighRiskCountry from "../Views/RemitHighRiskCountry/RemitHighRiskCountry";
import IdTypeSummary from "../Views/IdTypeSummary/IdTypeSummary";
import AddIdtypeSummary from "../Components/AddIdtypeSummary/AddIdtypeSummary";
import KYCCustomerEnquiry from "../Views/CustomerEnquiry/CustomerEnquiry";
import OTPTempTable from "../Views/OTPTempTable/OTPTempTable";
import IdDocMapping from "../Views/IdDocMapping/IdDocMapping";
import WalletSizeSetup from "../Views/WalletSizeSetup/WalletSizeSetup";
import EditWalletSizeSetup from "../Components/EditWalletSizeSetup/EditWalletSizeSetup";
import WalletSizeBrandMapping from "../Views/WalletSizeBrandMapping/WalletSizeBrandMapping";
import EditWalletSizeBrandMapping from "../Components/EditWalletSizeBrandMapping/EditWalletSizeBrandMapping";
import CardUpgradeView from "../Components/CardUpgradeView/CardUpgradeView";
import CardType from "../Views/CardType/CardType";
import ExpairyWalletDowngrade from "../Views/KycExpairyWallet/KycExpairyWalletDowngrade";
import KycBlockAfterGrace from "../Views/KycBlockAfterGrace/KycBlockAfterGrace";
import IdExpiringReports from "../Views/IdExpiringReports/IdExpiringReports";
import RemitAMLComplianceConfig from "../Views/RemitAMLComplianceConfig/RemitAMLComplianceConfig";
import BlockCardPending from "../Views/BlockCardPending/BlockCardPending";
import BlockCardApproved from "../Views/BlockCardApproved/BlockCardApproved";
import BlockCardRejected from "../Views/BlockCardRejected/BlockCardRejected";
import BlockCardError from "../Views/BlockCardError/BlockCardError";
import TargetGroup from "../Views/TargetGroup/TargetGroup";
import UnblockCardPending from "../Views/UnblockCardPending/UnblockCardPending";
import UnblockCardApproved from "../Views/UnblockCardApproved/UnblockCardApproved";
import UnblockCardRejected from "../Views/UnBlockCardRejected/UnblockCardRejected";
import UnblockCardError from "../Views/UnblockCardError/UnblockCardError";
import KYCUpdatePending from "../Views/KYCUpdatePending/KYCUpdatePending";
import KYCUpdateApproved from "../Views/KYCUpdateCardApproved/KYCUpdateApproved";
import KYCUpdateRejected from "../Views/KYCUpdateCardRejected/KYCUpdateRejected";
import KYCUpdateError from "../Views/KYCUpdateCardError/KYCUpdateError";
import WalletPending from "../Views/WalletUpgradePending/WalletPending";
import WalletApproved from "../Views/WalletUpgradeApproved/WalletApproved";
import WalletRejected from "../Views/WalletUpgradeRejected/WalletRejected";
import WalletError from "../Views/WalletUpgradeError/WalletError";
import DailyTransactionReport from "../Views/DailyTranscationReport/DailyTranscationReport";
import MonthlyTransactionReport from "../Views/MonthlyTransactionReport/MonthlyTransactionReport";
import RefundTransactionReport from "../Views/RefundTransactionReport/RefundTransactionReport";
import OnBehalfSenderReport from "../Views/OnBehalfSenderReport/OnBehalfSenderReport";
import UAMreport from "../Views/UAMreport/UAMreport";
import MIRSDeclinedTransactionReport from "../Views/MIRSDeclinedTransactionReport/MIRSDeclinedTransactionReport";
import RejectedTransactionReport from "../Views/RejectedTransactionReport/RejectedTransactionReport";
import TransactionSummaryReport from "../Views/TransactionSummaryReport/TransactionSummaryReport";
import TransactionReport from "../Views/TransactionRepots/TransactionRepots";
import EndofDayReport from "../Views/EndOfDayReport/EndofDayReport";
import FailedTxnReport from "../Views/FailedTxnReport/FailedTxnReport";
import BranchManagementReport from "../Views/BranchManagementReport/BranchManagementReport";
import CustomerLoginReport from "../Views/CustomerLoginReport/CustomerLoginReport";
import AMLCFTReports from "../Views/AMLCFTReports/AMLCFTReports";
import CustomerRiskProfilingReport from "../Views/CustomerRiskProfilingReport/CustomerRiskProfilingReport";
import ECDDReport from "../Views/ECDDReport/ECDDReport";
import CustomerRiskSummaryReport from "../Views/CustomerRiskSummaryReport/CustomerRiskSummaryReport";
import OnBoardingSummaryReport from "../Views/OnboardingSummaryReport/OnboardingSummaryReport";
import MSSLTrackerListReport from "../Views/MSSLTrackerListReport/MSSLTrackerListReport";
import GroupNameSummaryReport from "../Views/GroupNameSummaryReport/GroupNameSummaryReport";
import MaintenanceListReport from "../Views/MaintenanceListReport/MaintenanceListReport";
import PromoCodeSummary from "../Views/PromoCodeSummary/PromoCodeSummary";
import AMLTransactionSummaryReport from "../Views/AMLTxnSummaryReport/AMLTransactionSummaryReport";
import PayrollCompanyCreation from "../Views/PayrollCompanyCreation/PayrollCompanyCreation";
import TopupReconciliationReport from "../Views/TopupReconciliationReport/TopupReconciliationReport";
import PrefundReconciliationReports from "../Views/PrefundReconciliationReport/PrefundReconciliationReport";
import PayrollSummaryReport from "../Views/PayrollSummaryReport/PayrollSummaryReport";
import PayrollDetailReport from "../Views/PayrollDetailReport​/PayrollDetailReport​";
import PrefundAmountReport from "../Views/PrefundAmountReport/PrefundAmountReport";
import PrefundDebitReport from "../Views/PrefundDebitReport​/PrefundDebitReport​";
import PrefundCreditReport from "../Views/PrefundCreditReport​/PrefundCreditReport​";
import ExchangeRate from "../Views/ExchangeRate/ExchangeRate";
import CustomerEnquiryView from "../Views/CustomerEnquiryView/CustomerEnquiryView";
import ValyouSRHCT from "../Views/ValyouSRHCT/ValyouSRHCT";
import AccountSummary from "../Views/AccountSummary/AccountSummary";
import auditTrialReport from "../Views/AuditTrial/AuditTrialreport";
import AuditTrialReport from "../Views/AuditTrial/AuditTrialreport";
import OnBoardingDetailsReport from "../Views/OnboardingDetailsReport/OnboardingDetailsReport";
import AddWalletFeature from "../Views/AddWalletFeature/AddWalletFeature";
import CustomerscreenReport from "../Views/CustomerScreenReport/CustomerScreenReport";
import MarketingReport from "../Views/MarketingReport/MarketingReport";
import Salesreport from "../Views/SalesReport/Salesreport";
import BoFunctionalCode from "../Views/BO_FunctionalCodes/BoFunctionalcode";
import BoFunctionalCodeEdit from "../Views/BOFunctionalCodeEdit/BOFunctionalCodeEdit";
import BOFunctionalCodeAdd from "../Views/BOFunctionalCodeADD/BOFunctioanlCodeAdd";
import PrefundBalanceByCompany from "../Views/PrefundBalanceByCompany/PrefundBalanceByCompany";
import SmsTransactionReport from "../Views/SmsTransactionReport/SmsTransactionReport";
import PayrollTxnByCompany from "../Views/PayrollTxnByCompany/PayrollTxnByCompany";
import Merchantsetup from "../Views/Merchantsetup/Merchantsetup";
import AvgDailyMonthlyTransactionReport from "../Views/AvgDailyMonthlyReportComparsion/AvgDailyMonthlyTxnReport";
import WalletDowngradeReport from "../Views/WalletDowngrade/WalletDowngradeReport";
import TopUpCommonReport from "../Views/Top-UpCommonReport/TopUpCommonReport";
import MerchantBranchSummary from "../Views/MerchantBranchSummary/MerchantBranchSummary";
import MerchantTellerSummary from "../Views/MerchantTellerSummary/MerchantTellerSummary";
import TransactionHistoryReport from "../Views/TransactionHistoryReport/TransactionHistoryReport";
import LanguageParameter from "../Views/LanguageParameter/LanguageParameter";
import LanguageParameterEdit from "../Views/LanguageParameter/LanguageParametersEdit/LanguageParameterEdit";
// import LanguageParameterAdd from '../Views/LanguageParameter/LanguageParameterEditll';
import MerchantSummaryHq from "../Views/MerchantSummaryHQ/MerchantSummaryHq";
import MerchantSummaryHQ from "../Views/MerchantSummaryHQ/MerchantSummaryHq";
import MerchantSummaryAdd from "../Views/MerchantSummaryHQ/MerchantSummaryAdd";
import MerchantSummaryView from "../Views/MerchantSummaryView/MerchantSummaryView";
import MerchantSummaryHQEdit from "../Views/MerchantSummaryHQEdit/MerchantSummaryHQEdit";
import payrollPrefund from "../Views/PayrollPrefund/payrollPrefund";
import LanguageParameterView from "../Views/LanguageParameter/LanguageParameterView/LanguageParameterView";
import LanguageParameterAdd from "../Views/LanguageParameter/LanguageParameterAdd/LanguageParameterAdd";
import ManualDebitCreditSummary from "../Views/ManualDebitCreditSummary/ManualDebitCreditSummary";
import PayrollPrefundApproval from "../Views/PayrollPrefundApproval/PayrollPrefundApproval";

const functionalCodeRoutes = [
  {
    name: "Security Management",
    functionalName: "",
    path: "",
    isLevelTwo: true,
    subMenu: true,
    sidebar: true,
    key: "sub2",
    layout: "/dashboard",
    menuItems: [
      {
        name: "User Access Management",
        functionalCode: "",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "BOSetup1",
        additionalMenuItems: [
          {
            path: "/User",
            name: "User",
            layout: "/dashboard/user-Access-Management",
            icon: <IoArrowForward />,
            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/user Access Management/User",
            component: UserDetails,
            functionalCode: "USER",
          },
          {
            path: "/User-Groups",
            name: "User Group",
            layout: "/dashboard/user-Access-Management",
            visibleInMenu: true,
            icon: <IoArrowForward />,
            secondSubmenu: false,
            key: "/dashboard/user-Access-Management/User-Groups",
            component: UserGroups,
            functionalCode: "Groups",
          },

          {
            path: "/User-Groups/Edit-User-Group",
            name: "User Group",
            layout: "/dashboard/user-Access-Management",
            icon: <IoArrowForward />,
            visibleInMenu: false,
            secondSubmenu: false,
            component: CreateUserGroup,
            functionalCode: "EDIT_USER_GROUP",
          },
          {
            path: "/User-Rights",
            name: "Users Rights",
            layout: "/dashboard/user-Access-Management",
            icon: <IoArrowForward />,
            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/user Access Management/User Rights",
            component: UserRights,
            functionalCode: "USR_RGTS",
          },
          {
            path: "/Group-Rights",
            name: "Group Rights",
            layout: "/dashboard/user-Access-Management",
            icon: <IoArrowForward />,
            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/user Acess Management/Group Rights",
            component: GroupRights,
            functionalCode: "GROUP_RIGHTS",
          },
        ],
      },
      {
        name: "Security Operations",
        functionalCode: "TEST",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "UnlockAccount",
        additionalMenuItems: [
          {
            path: "/unlock",
            name: "Unlock Customer Mobile or Device",
            layout: "/dashboard/User-Account-Unlock",
            icon: <IoArrowForward />,
            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/user Account Unlock/User",
            component: LockedCustomer,
            functionalCode: "UNLOCK_CUS_ACC",
          },
          {
            path: "/Customer-Login-Records",
            name: "Customer Login Records",
            layout: "/dashboard/User-Account-Unlock",
            icon: <IoArrowForward />,
            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/user Account Unlock/User",
            component: UserLoginRecords,
            functionalCode: "CUS_LOGIN_REC",
          },
          {
            path: "/Locked-Account-History",
            name: "Account and Device History",
            layout: "/dashboard/User-Account-Unlock",
            icon: <IoArrowForward />,
            visibleInMenu: false,
            secondSubmenu: false,
            key: "/dashboard/user Account Unlock/User",
            component: DeviceMobileHistory,
            functionalCode: "MOBILE_AND_DEV_HISTORY",
          },
          {
            path: "/Locked-Device-History",
            name: "Lock/UnLock Device History",
            layout: "/dashboard/User-Account-Unlock",
            icon: <IoArrowForward />,
            visibleInMenu: false,
            secondSubmenu: false,
            key: "/dashboard/user Account Unlock/User",
            component: LockedDeviceHistory,
            functionalCode: "MOBILE_AND_DEV_HISTORY",
          },
          {
            path: "/unlock-staff",
            name: "Unlock BO User",
            layout: "/dashboard/User-Account-Unlock",
            icon: <IoArrowForward />,
            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/user Account Unlock/User",
            component: LockedBackOfficeUser,
            functionalCode: "UNLOCK_BO_ACC",
          },
          {
            path: "/block-mobile-device",
            name: "Lock Account / Device ",
            layout: "/dashboard/User-Account-Unlock",
            icon: <IoArrowForward />,
            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/user Account Unlock/User",
            component: BlockNumberDevice,
            functionalCode: "DEV_LOCK_OR_UNLOCK",
          },
          {
            path: "/Global-Settings-Mobile",
            name: "Global Settings",
            layout: "/dashboard/User-Account-Unlock",
            icon: <IoArrowForward />,
            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/user Account Unlock/User",
            component: GlobalSettings,
            functionalCode: "GLOBAL_SETTINGS",
          },
          {
            path: "/Global-Settings-Device",
            name: "Global Settings Devcice",
            layout: "/dashboard/User-Account-Unlock",
            icon: <IoArrowForward />,
            visibleInMenu: false,
            secondSubmenu: false,
            key: "/dashboard/user Account Unlock/User",
            component: GlobalSettingsDevice,
            functionalCode: "GLOBAL_SETT",
          },

          {
            path: "/Add-New",
            name: "Add New",
            layout: "/dashboard/User-Account-Unlock",
            icon: <IoArrowForward />,
            visibleInMenu: false,
            secondSubmenu: false,
            key: "/dashboard/user Account Unlock/User",
            component: GroupRights,
            functionalCode: "USER_ACCOUNT_UNLOCK_USER",
          },
        ],
      },
    ],
  },
  {
    name: "Setup and Configuration",
    functionalName: "",
    path: "",
    isLevelTwo: true,
    subMenu: true,
    sidebar: true,
    key: "sub3",
    layout: "/dashboard",
    menuItems: [
      {
        name: "Branch Management",
        functionalCode: "BRANCH_MANAGEMENT",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "BOSetup7",
        additionalMenuItems: [
          {
            path: "/Agent-Group",
            name: "Agent Group",
            functionalCode: "AGENT_DASHBOARD",
            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/Branch-Management",
            layout: "/dashboard/Branch-Management",
            component: AgentGroup,
          },
          {
            path: "/Branch-Dashboard",
            name: "Branch Dashboard",
            functionalCode: "BRANCH_DASHBOARD",

            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/Branch-Management",
            layout: "/dashboard/Branch-Management",
            component: BranchDashboard,
          },
          {
            path: "/Add-Branch",
            name: "Add Branch",
            functionalCode: "BRANCH_DASHBOARD",

            visibleInMenu: false,
            secondSubmenu: false,
            key: "/dashboard/Branch-Management/Branch-Dashboard",
            layout: "/dashboard/Branch-Management/Branch-Dashboard",
            component: AddBranch,
          },
          {
            path: "/Terminal-Dashboard",
            name: "Terminal Dashboard",
            functionalCode: "E_TERMINAL",

            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/Branch-Management",
            layout: "/dashboard/Branch-Management",
            component: TerminalDashboard,
          },

          {
            path: "/Add-ETerminal",
            name: "Add ETerminal",
            functionalCode: "E_TERMINAL",

            visibleInMenu: false,
            secondSubmenu: false,
            key: "/dashboard/Branch-Management/Terminal-Dashboard",
            layout: "/dashboard/Branch-Management/Terminal-Dashboard",
            component: AddETerminal,
          },
          {
            path: "/Edit-ETerminal",
            name: "Edit ETerminal",
            functionalCode: "E_TERMINAL",

            visibleInMenu: false,
            secondSubmenu: false,
            key: "/dashboard/Branch-Management/Terminal-Dashboard",
            layout: "/dashboard/Branch-Management/Terminal-Dashboard",
            component: AddETerminal,
          },
        ],
      },
      {
        name: "Notification Setup",
        functionalCode: "NOTIFICATION_SETUP",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "setupNotification",
        additionalMenuItems: [
          {
            path: "/Notification-Master-Setup",
            name: "Notification Master",
            functionalCode: "NOTIFICATION_MASTER",
            L2functionalName: "Notification",
            visibleInMenu: true,
            key: "/dashboard/Notification-Master-Setup",
            layout: "/dashboard",
            component: NotificationMasterSetup,
          },
          {
            path: "/notification-master-view",
            name: "Notification Master View",
            functionalCode: "NOTIFICATION_MASTER",
            L2functionalName: "Notification",
            visibleInMenu: false,
            key: "/dashboard",
            layout: "/dashboard",
            component: NotificationMasterForm,
          },
          {
            path: "/notification-channel",
            name: "Notification Channel",
            functionalCode: "NOTIFICATION_CHANNEL",
            L2functionalName: "Notification",
            visibleInMenu: true,
            key: "/dashboard",
            layout: "/dashboard",
            component: NotificationChannelSetup,
          },
          {
            path: "/notification-channel-view",
            name: "Notification Channel view",
            functionalCode: "NOTIFICATION_CHANNEL",
            L2functionalName: "Notification",
            visibleInMenu: false,
            key: "/dashboard",
            layout: "/dashboard",
            component: NotificationChannelSetup,
          },
          {
            path: "/notification-channel-edit",
            name: "Notification Channel Edit",
            functionalCode: "NOTIFICATION_CHANNEL",
            L2functionalName: "Notification",
            visibleInMenu: false,
            key: "/dashboard",
            layout: "/dashboard",
            component: NotificationChannelEdit,
          },
        ],
      },

      {
        name: "BO-Setups",
        functionalCode: "TEST",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "BOSetup2",
        additionalMenuItems: [
          {
            path: "/reference-data",
            name: "Reference Data",
            functionalCode: "REF_DATA",
            L2functionalName: "ReferenceData",
            visibleInMenu: true,
            key: "/dashboard/reference-data",
            layout: "/dashboard",
            component: ReferenceData,
          },

          {
            path: "/create-new-code",
            name: "Create New Code",
            functionalCode: "REF_DATA",
            L2functionalName: "create-new-code",
            visibleInMenu: false,
            key: "/dashboard/reference-data/create-new-code",
            layout: "/dashboard/reference-data",
            component: ReferenceDataCreate,
          },
          {
            path: "/edit-code",
            name: "Edit Code",
            functionalCode: "REF_DATA",
            L2functionalName: "Edit Code",
            visibleInMenu: false,
            key: "/dashboard/reference-data/edit-code",
            layout: "/dashboard/reference-data",
            component: ReferenceDataEdit,
          },
          {
            path: "/ID-Type-Routing",
            name: "Id Type Routing",
            functionalCode: "ID_TYPE_REG",
            //functionalCode: "ID_TYPE_SUMMARY",

            L2functionalName: "Id Type Routing",
            visibleInMenu: true,
            key: "/dashboard/ID-Type-Routing",
            layout: "/dashboard",
            component: IdTypeRouting,
          },
          {
            path: "/ID-Type-Create",
            name: "ID-Type-Create",
            functionalCode: "ID_TYPE_REG",
            L2functionalName: "ID-Type-Create",
            visibleInMenu: false,
            key: "/dashboard/ID-Type-Routing/ID-Type-Create",
            layout: "/dashboard/ID-Type-Routing",
            component: IdTypeCreate,
          },
          {
            path: "/ID-Type-Edit",
            name: "ID-Type-Edit",
            functionalCode: "ID_TYPE_REG",
            L2functionalName: "ID-Type-Edit",
            visibleInMenu: false,
            key: "/dashboard/ID-Type-Routing/ID-Type-Edit",
            layout: "/dashboard/ID-Type-Routing",
            component: IdTypeEdit,
          },
          {
            path: "/Functional-code",
            name: "Function Code Setup",
            functionalCode: "ID_TYPE_REG",
            L2functionalName: "Function code",
            visibleInMenu: true,
            key: "/dashboard/Functional-code",
            layout: "/dashboard",
            component: BoFunctionalCode,
          },
          {
            path: "/FunctionalCode-Create",
            name: "Functional Code Setup-Create",
            functionalCode: "ID_TYPE_REG",
            L2functionalName: "Functional Code-Create",
            visibleInMenu: false,
            key: "/dashboard/Functional-code/Functional-code-Create",
            layout: "/dashboard/Functional-code",
            component: BOFunctionalCodeAdd,
          },
          {
            path: "/FunctionalCode-Edit",
            name: "Function Code Setup-Edit",
            functionalCode: "ID_TYPE_REG",
            L2functionalName: "Function Code-Edit",
            visibleInMenu: false,
            key: "/dashboard/Functional-code/Functional-code-Edit",
            layout: "/dashboard/Functional-code",
            component: BoFunctionalCodeEdit,
          },
        ],
      },
      {
        name: "IdType",
        functionalCode: "",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "BOSetup3",
        additionalMenuItems: [
          {
            path: "/Idtype-Summary",
            name: "ID Type Summary",
            functionalCode: "E_TERMINAL",
            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/Idtype-Summary",
            layout: "/dashboard",
            component: IdTypeSummary,
          },
          {
            path: "/Add-Idtype-Summary",
            name: "Add ID Type",
            functionalCode: "E_TERMINAL",
            visibleInMenu: false,
            secondSubmenu: false,
            key: "/dashboard/Idtype-Summary/Add-Idtype-Summary",
            layout: "/dashboard/Idtype-Summary",
            component: AddIdtypeSummary,
          },
          {
            path: "/Edit-Idtype-Summary",
            name: "Edit ID Type",
            functionalCode: "E_TERMINAL",
            visibleInMenu: false,
            secondSubmenu: false,
            key: "/dashboard/Idtype-Summary/Edit-Idtype-Summary",
            layout: "/dashboard/Idtype-Summary",
            component: AddIdtypeSummary,
          },
          {
            path: "/View-Idtype-Summary",
            name: "View ID Type",
            functionalCode: "E_TERMINAL",
            visibleInMenu: false,
            secondSubmenu: false,
            key: "/dashboard/Idtype-Summary/View-Idtype-Summary",
            layout: "/dashboard/Idtype-Summary",
            component: AddIdtypeSummary,
          },
        ],
      },
      {
        name: "Wallet",
        functionalCode: "",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "walletFeature",
        additionalMenuItems: [
          {
            path: "/addwalletfeature",
            name: "Add Wallet Feature",
            functionalCode: "WALLET",
            L2functionalName: "Add Wallet Feature",
            visibleInMenu: false,
            key: "/dashboard/addwalletfeature",
            layout: "/dashboard/wallet",
            component: AddWalletFeature,
          },
          {
            path: "/walletFeatureSummary",
            name: "Wallet Feature Summary",
            functionalCode: "WALLET",
            L2functionalName: "Wallet Feature Summary",
            visibleInMenu: true,
            key: "/dashboard/wallet",
            layout: "/dashboard/wallet",
            component: AddWalletFeature,
          },
        ],
      },
      {
        name: "noSubmenu",
        functionalCode: "",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "BOSetup_6",
        additionalMenuItems: [
          {
            path: "/ID-Doc-Mapping",
            name: "Brand - ID Doc Mapping",
            functionalCode: "BRAND_ID_DOC_MAP",
            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/Setup-And-Configuration",
            layout: "/dashboard/Setup-And-Configuration",
            component: IdDocMapping,
          },
          {
            path: "/Wallet-Size-Setup",
            name: "Wallet Size Setup",
            functionalCode: "WALLET-SIZE-SETUP",
            L2functionalName: "Wallet Size Setup",
            visibleInMenu: true,
            key: "/dashboard/Wallet-Size-Setup",
            layout: "/dashboard",
            component: WalletSizeSetup,
          },
          {
            path: "/Wallet-Size-Brand-Mapping",
            name: "Wallet Size Brand Mapping",
            functionalCode: "WALLET_SIZE_BRAND_MAPPING",
            L2functionalName: "Wallet Size Brand Mapping",
            visibleInMenu: true,
            key: "/dashboard/Wallet-Size-Brand-Mapping",
            layout: "/dashboard",
            component: WalletSizeBrandMapping,
          },
          {
            path: "/Edit-Wallet-Size",
            name: "Edit Wallet Size",

            functionalCode: "EDIT_WALLET_SIZE",

            L2functionalName: "Edit Wallet Size",
            visibleInMenu: false,
            key: "/dashboard/Wallet-Size-Setup/Edit-Wallet-Size",
            layout: "/dashboard/Wallet-Size-Setup",
            component: EditWalletSizeSetup,
          },
          {
            path: "/Edit",
            name: "Edit",

            functionalCode: "WALLET-SIZE-SETUP_EDIT",

            L2functionalName: "Edit",
            visibleInMenu: false,
            key: "/dashboard/Wallet-Size-Brand-Mapping/Edit",
            layout: "/dashboard/Wallet-Size-Brand-Mapping",
            component: EditWalletSizeBrandMapping,
          },
          {
            path: "/Card-type",
            name: "Card Setup",
            functionalCode: "CARD_TYPE",
            L2functionalName: "Card Type",
            visibleInMenu: true,
            key: "/dashboard/Setup-And-Configuration",
            layout: "/dashboard/Setup-And-Configuration",
            component: CardType,
          },
          {
            path: "/Language-Parameter",
            name: "Language Parameter",
            functionalCode: "LANGUAGE_PARAMETER",
            visibleInMenu: true,
            key: "/dashboard/Setup-And-Configuration",
            layout: "/dashboard/Setup-And-Configuration",
            component: LanguageParameter,
          },
          {
            path: "/Language-Parameter-view",
            name: "Language Parameter View",
            functionalCode: "LANGUAGE_PARAMETER_VIEW",
            visibleInMenu: false,
            key: "/dashboard",
            layout: "/dashboard",
            component: LanguageParameterView,
          },
          {
            path: "/Language-Parameter-edit",
            name: "Language Parameter edit",
            functionalCode: "LANGUAGE_PARAMETER_EDIT",
            visibleInMenu: false,
            key: "/dashboard",
            layout: "/dashboard",
            component: LanguageParameterEdit,
          },
          {
            path: "/Language-Parameter-add",
            name: "Language Parameter add",
            functionalCode: "LANGUAGE_PARAMETER_ADD",
            visibleInMenu: false,
            key: "/dashboard",
            layout: "/dashboard",
            component: LanguageParameterAdd,
          },
        ],
      },
    ],
  },
  {
    name: "Remittance",
    functionalName: "",
    path: "",
    isLevelTwo: true,
    subMenu: true,
    sidebar: true,
    key: "remit",
    layout: "/dashboard",
    menuItems: [
      {
        name: "Remittance BO Setup",
        functionalCode: "REMITTANCE_BO_SETUP",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "remittance",
        additionalMenuItems: [
          {
            path: "/Payout-Country",
            name: "Payout Country",
            functionalCode: "PAYOUT_COUNTRY",
            L2functionalName: "Payout Country",
            visibleInMenu: true,
            key: "/dashboard/remit-setup",
            layout: "/dashboard/remit-setup",
            component: RemitCountrySetup,
          },
          {
            path: "/Bank-Setup",
            name: "Bank Setup",
            functionalCode: "BANK",
            L2functionalName: "Bank Setup",
            visibleInMenu: true,
            key: "/dashboard/remit-setup",
            layout: "/dashboard/remit-setup",
            component: RemitBankSetup,
          },
          {
            path: "/View-Bank-Setup",
            name: "View Bank Setup",
            functionalCode: "BANK",
            L2functionalName: "Bank Setup",
            visibleInMenu: false,
            key: "/dashboard/remit-setup/Bank-Setup",
            layout: "/dashboard/remit-setup/Bank-Setup",
            component: RemitBankForm,
          },
          {
            path: "/Branch-Setup",
            name: "Branch Setup",
            functionalCode: "BRANCH",
            L2functionalName: "Branch Setup",
            visibleInMenu: true,
            key: "/dashboard/remit-setup",
            layout: "/dashboard/remit-setup",
            component: RemitBranchSetup,
          },
          {
            path: "/Paying-Group",
            name: "Paying Group",
            functionalCode: "PAYING_GROUP",
            L2functionalName: "Paying Group",
            visibleInMenu: true,
            key: "/dashboard/remit-setup",
            layout: "/dashboard/remit-setup",
            component: RemitAgentTag,
          },
          {
            path: "/Remittance-Transaction-Processing",
            name: "Remittance Txn Processing",
            functionalCode: "REMITTANCE_TXN_PROCESSING",
            L2functionalName: "Remittance Txn Processing",
            visibleInMenu: true,
            key: "/dashboard/remit-setup",
            layout: "/dashboard/remit-setup",
            component: RemitTransactionProcessing,
          },
          {
            path: "/Remittance-Transaction-Enquiry",
            name: "Remittance Transaction Enquiry Details",
            functionalCode: "REMITTANCE_TRANSACTION_ENQUIRY",
            L2functionalName: "Remittance Txn Enquiry Details",
            visibleInMenu: false,
            key: "/dashboard/remit-setup",
            layout: "/dashboard/remit-setup",
            component: RemitTransactionEnquiry,
          },
          {
            path: "/Edit-On-Behalf-Details",
            name: "Edit On Behalf Details",
            functionalCode: "EDIT_ON_BEHALF_DETAILS",
            L2functionalName: "Edit On Behalf Details",
            visibleInMenu: false,
            key: "/dashboard/remit-setup",
            layout: "/dashboard/remit-setup",
            component: RemitEditOnBehalf,
          },
          {
            path: "/Remittance-Transaction-Status-Dashboard",
            name: "Remittance Txn Status Dashboard",
            functionalCode: "REMITTANCE_TRANSACTION_STATUS_DASHBORD",
            L2functionalName: "Remittance Txn Status Dashboard",
            visibleInMenu: false,
            key: "/dashboard/remit-setup",
            layout: "/dashboard/remit-setup",
            component: RemitTransactionStatus,
          },
          {
            path: "/Remittance-Transaction-Status",
            name: "Remittance Txn Status",
            functionalCode: "REMITTACNE_TRANSACTION_STATUS",
            L2functionalName: "Remittance Txn Status",
            visibleInMenu: false,
            key: "/dashboard/remit-setup",
            layout: "/dashboard/remit-setup",
            component: RemitTransactionStatus,
          },
          {
            path: "/Remittance-Fees-And-Charges",
            name: "Remittance Fees And Charges",
            functionalCode: "REMIT_FEES_CHARGES",
            L2functionalName: "Remittance Fees And Charges",
            visibleInMenu: true,
            key: "/dashboard/remit-setup",
            layout: "/dashboard/remit-setup",
            component: RemittanceFeesAndCharges,
          },
          {
            path: "/Remittance-Transaction-Status-Limit",
            name: "Remittance Transaction Limit",
            functionalCode: "REMITTANCE ",
            L2functionalName: "Remittance Transaction Limit",
            visibleInMenu: false,
            key: "/dashboard/remit-setup",
            layout: "/dashboard/remit-setup",
            component: RemitTransactionLimit,
          },
          {
            path: "/Transaction-Status-Limit",
            name: "Remittance Transaction Limit Setup",
            functionalCode: "REMITTANCE_TRANSACTION_LIMIT_SETUP",

            L2functionalName: "Remittance Transaction Limit Setup",
            visibleInMenu: true,
            key: "/dashboard/remit-setup",
            layout: "/dashboard/remit-setup",
            component: RemittanceAddLimit,
          },
          {
            path: "/ECDD-Setup",
            name: "ECDD Setup",
            functionalCode: "ECDD_SETUP",
            L2functionalName: "ECDD Setup",
            visibleInMenu: true,
            key: "/dashboard/ECDD-Setup",
            layout: "/dashboard/remit-setup",
            component: AmlEcddSetup,
          },
          {
            path: "/Risk-Score",
            name: "Risk Score",
            functionalCode: "RISK_SCORE",
            L2functionalName: "Risk Score",
            visibleInMenu: true,
            key: "/dashboard/Risk-Score",
            layout: "/dashboard/remit-setup",
            component: AmlRiskScale,
          },
          {
            path: "/Transaction-Statistics",
            name: "Transaction Statistics",
            functionalCode: "TRANSAC_STATISTICS",
            L2functionalName: "Transaction Statistics",
            visibleInMenu: true,
            key: "/dashboard/Transaction-Statistics",
            layout: "/dashboard/remit-setup",
            component: AmlTransactionStatistics,
          },
          {
            path: "/Risk-Factor",
            name: "Risk Factor",
            functionalCode: "RISK_FACTOR",
            L2functionalName: "Risk Factor",
            visibleInMenu: true,
            key: "/dashboard/Risk-Factor",
            layout: "/dashboard/remit-setup",
            component: RemitRiskFactor,
          },
          {
            path: "/Risk-Factor-Status-Configuration",
            name: "Risk Factor Status Configuration",
            functionalCode: "RISK_FACTOR_STATUS_CONFIGURATION",
            L2functionalName: "/Risk Factor Status Configuration",
            visibleInMenu: false,
            key: "/dashboard/Risk-Factor-Status-Configuration",
            layout: "/dashboard/remit-setup",
            component: RemitRiskFactorStatusConfiguration,
          },
          {
            path: "/Risk-Rating",
            name: "Risk Rating",
            functionalCode: "RISK_RATING",
            L2functionalName: "Risk Rating",
            visibleInMenu: true,
            key: "/dashboard/Risk-Rating",
            layout: "/dashboard/remit-setup",
            component: RemitRiskRating,
          },
          {
            path: "/Exchange-Rate",
            name: "Exchange Rate",

            functionalCode: "EXCHANGE_RATE",
            L2functionalName: "Exchange Rate",
            visibleInMenu: true,
            key: "/dashboard/Exchange-Rate",
            layout: "/dashboard/remit-setup",
            component: ExchangeRate,
          },
          {
            path: "/High-Risk-Country-Setup",
            name: "HRC(High Risk Country) Setup",
            functionalCode: "HIGH_RISK_COUNTRY",
            L2functionalName: "High Risk Country Setup",
            visibleInMenu: true,
            key: "/dashboard/High-Risk-Country-Setup",
            layout: "/dashboard/remit-setup",
            component: RemitHighRiskCountry,
          },
          {
            path: "/Remit-AML-Compliance-Config",
            name: "Remit AML Compliance Config",

            functionalCode: "REMIT_AML_CONFIG",

            L2functionalName: "Remit AML Compliance Config",
            visibleInMenu: true,
            key: "/dashboard/Remit-AML-Compliance-Config",
            layout: "/dashboard/remit-setup",
            component: RemitAMLComplianceConfig,
          },
          {
            path: "/Target-Group-Setup",
            name: "Target Group",
            functionalCode: "TARGET_GROUP",
            L2functionalName: "Target Group",
            visibleInMenu: true,
            key: "/dashboard/Target-Group-Setup",
            layout: "/dashboard/marketing",
            component: TargetGroup,
          },
          {
            path: "/Promo-Code-Summary",
            name: "Promo Code Summary",
            functionalCode: "PROMO_CODE_SETUP",
            L2functionalName: "Promo Code Summary",
            visibleInMenu: true,
            key: "/dashboard/Promo-Code-Summary",
            layout: "/dashboard/marketing",
            component: PromoCodeSummary,
          },
        ],
      },
    ],
  },
  {
    name: "Payroll",
    functionalName: "",
    path: "",
    isLevelTwo: true,
    subMenu: true,
    sidebar: true,
    key: "sub4",
    layout: "/dashboard",
    menuItems: [
      {
        name: "noSubmenu",
        functionalCode: "TEST",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: false,
        layout: "/dashboard",
        key: "BOSetup6",
        additionalMenuItems: [
          {
            path: "/company-maintenance",
            name: "Company Maintenance",
            functionalCode: "COMP_MAIN",
            L2functionalName: "ID-Type-Edit",
            visibleInMenu: true,
            layout: "/dashboard/Payroll-Company-Management",
            key: "/dashboard/Payroll-Company-Management",
            component: CompanyMaintenanceScreen,
          },
          {
            path: "/Add-Company-Maintenance",
            name: "Company Maintenance",
            functionalCode: "COMP_MAIN",
            L2functionalName: "ID-Type-Edit",
            visibleInMenu: false,
            layout: "/dashboard/Payroll-Company-Management/company-maintenance",
            key: "/dashboard/Payroll-Company-Management",
            component: CompanyMaintenanceScreen,
          },
          {
            path: "/Company-User",
            name: "Link Company User",
            layout: "/dashboard/Company-UserScreen",
            functionalCode: "COMPANY_USER_MAPPING",
            L2functionalName: "KYC Customer",
            visibleInMenu: true,
            key: "/dashboard/Company-UserScreen",
            component: CompanyUserScreenList,
          },
          {
            path: "/account-transaction",
            name: "Top Up Prefund Account",
            component: PreFundProcessing,
            functionalCode: "ACCOUNT_TRANSACTION",
            L2functionalName: "ID-Type-Edit",
            visibleInMenu: true,
            layout: "/dashboard",
            key: "account-transaction",
          },
          {
            path: "/Add-account-transaction",
            name: "ADD-TopUp Prefund Account",
            component: AccountTransaction,
            functionalCode: "COMP_MAIN",
            L2functionalName: "ID-Type-Edit",
            visibleInMenu: false,
            layout: "/dashboard/account-transaction",
            key: "account-transaction",
          },
          {
            path: "/Topup-Add",
            name: "Topup Add",
            functionalCode: "SAL_PAY",
            L2functionalName: "Topup Add",
            visibleInMenu: true,
            key: "/dashboard/Topup-Add",
            layout: "/dashboard",
            component: TopUpAdd,
          },
          {
            path: "/payroll-enquiry",
            name: " Company Account Enquiry",
            functionalCode: "COM_PREF_ACC_TRANS_ENQ",
            L2functionalName: "ID-Type-Edit",
            visibleInMenu: false,
            layout: "/dashboard",
            key: "Payroll-enquiry",
            component: PayrollEnquirey,
          },
          {
            path: "/payroll-account",
            name: "COMPANY_USER_MAPPING",
            functionalCode: "PAYROLL_ACCOUNT",
            L2functionalName: "ID-Type-Edit",
            visibleInMenu: true,
            layout: "/dashboard",
            key: "Payroll-account",
            component: CompanyPayrollAccountEnquiry,
          },
          {
            path: "/prefund-Transaction-enquiry",
            name: "Prefund Transaction Enquiry",
            component: PrefundTransactionEnquiry,
            subMenu: false,
            sidebar: true,
            visibleInMenu: true,
            functionalCode: "PREFUND_TRANSACTION_ENQUIRY",

            layout: "/dashboard",
            key: "prefund-Transaction-enquiry",
          },
          {
            path: "/PreOnBoarding",
            name: "PreOnBoarding",
            functionalCode: "PRE_ONBOARDING",
            L2functionalName: "PreOnBoarding",
            visibleInMenu: true,
            key: "/dashboard/PreOnBoarding",
            layout: "/dashboard",
            component: PreOnBoarding,
          },
          {
            path: "/PreOnBoarding-Customer",
            name: "PreOnBoarding Customer",
            functionalCode: "PRE_ONBORDING_CUSTOMER",
            L2functionalName: "PreOnBoarding Customer",
            visibleInMenu: false,
            key: "/dashboard",
            layout: "/dashboard",
            component: PreOnBoardingCustomer,
          },
          {
            path: "/PayrollPrefund",
            name: "Payroll Prefund",
            functionalCode: "PAYROLL_PREFUND_COMPANY_USER",
            L2functionalName: "PreOnBoarding Customer",
            visibleInMenu: true,
            key: "/dashboard",
            layout: "/dashboard",
            component: payrollPrefund,
          },
          {
            path: "/PayrollPrefundApproval",
            name: "Payroll Prefund Approval",
            functionalCode: "PAYROLL_PREFUND_STAFF_L2_L3_CHECKER",
            L2functionalName: "PreOnBoarding Customer",
            visibleInMenu: true,
            key: "/dashboard",
            layout: "/dashboard",
            component: PayrollPrefundApproval,
          },
          {
            path: "/debit-credit-summary",
            name: "Manual Debit / Refund Summary",
            layout: "/dashboard/manual-debit-credit",
            icon: <IoArrowForward />,
            visibleInMenu: true,
            secondSubmenu: false,
            key: "/dashboard/Manual-Debit/Payroll-credit-summary",
            component: ManualDebitCreditSummary,
            functionalCode: "MANUAL_DEBIT_CREDIT",
          },
        ],
      },
    ],
  },
  {
    name: "Card Operations",
    functionalName: "",
    path: "",
    isLevelTwo: true,
    subMenu: true,
    sidebar: true,
    key: "wallet",
    layout: "/dashboard",
    menuItems: [
      {
        name: "noSubmenu",
        functionalCode: "SRF",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "walletSrf",
        additionalMenuItems: [
          {
            path: "/Block-Card-Request",
            name: "Block Card Request",
            functionalCode: "SRF_CARD_BLOCK",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: BlockCardRequest,
          },
          {
            path: "/Add-Block-Card-Request",
            name: "Add Block Card Request",
            functionalCode: "SRF_CARD_BLOCK",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: AddBlockCardRequest,
          },
          {
            path: "/View-Block-Card-Request",
            name: "Block Card Request View",
            functionalCode: "SRF_CARD_BLOCK",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: BlockCardRequestViewDetail,
          },
          {
            path: "/View-Block-Customer",
            name: "Block Card Customer View",
            functionalCode: "SRF_CARD_BLOCK",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: CustomerEnquiryView,
          },
          {
            path: "/Card-Replacement",
            name: "Card Replacement",
            functionalCode: "PAYING_GROUP",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: CardReplacement,
          },
          {
            path: "/Add-Card-Replacement",
            name: "Add Card Replacement",
            functionalCode: "PAYING_GROUP",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: AddCardReplacement,
          },
          {
            path: "/View-Card-Replacement",
            name: "View Card Replacement",
            functionalCode: "PAYING_GROUP",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: ViewCardReplacement,
          },
          {
            path: "/Card-Unblock",
            name: "Unblock Card Request",
            functionalCode: "SRF_CARD_UNBLOCK",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: CardUnblock,
          },
          {
            path: "/Card-Unblock-View-Details",
            name: "Card Unblock View Details",
            functionalCode: "SRF_CARD_UNBLOCK",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: CardUnblockView,
          },
          {
            path: "/View-UnBlock-Customer",
            name: "UnBlock Card Customer View",
            functionalCode: "SRF_CARD_UNBLOCK",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: CustomerEnquiryView,
          },
          {
            path: "/Add-Card-Unblock",
            name: "Add Card Unblock",
            functionalCode: "SRF_CARD_UNBLOCK",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: AddCardUnblock,
          },
          {
            path: "/Card-Upgrade",
            name: "Upgrade Wallet Size Request",
            functionalCode: "CARD_UPGRADE",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: CardUpgrade,
          },
          {
            path: "/Card-Upgrade-View-Details",
            name: "Card Upgrade View Details",
            functionalCode: "CARD_UPGRADE",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: CardUpgradeView,
          },
          {
            path: "/Card-Upgrade-View-Customer",
            name: "Card Upgrade View Customer",
            functionalCode: "CARD_UPGRADE",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: CustomerEnquiryView,
          },
          {
            path: "/Doc-Upload-Request",
            name: "Doc Upload Request",
            functionalCode: "DOCUMENT_UPLOAD",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: DocUploadRequest,
          },
          {
            path: "/Doc-Upload-Request-View",
            name: "Doc Upload Request View",
            functionalCode: "DOCUMENT_UPLOAD",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: DocUploadRequestView,
          },
          {
            path: "/Doc-Upload-Customer-View",
            name: "Doc Upload Customer View",
            functionalCode: "DOCUMENT_UPLOAD",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: CustomerEnquiryView,
          },
          {
            path: "/Doc-Upload-Request-Add",
            name: "Doc Upload Request Add",
            functionalCode: "DOCUMENT_UPLOAD",
            L2functionalName: "",
            visibleInMenu: false,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: DocUploadRequestAdd,
          },
          {
            path: "/Expiry-Wallet-Downgrade",
            name: "KYC Expiry Wallet Downgrade",
            functionalCode: "WALLET_DOWNGRADE",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: ExpairyWalletDowngrade,
          },
          {
            path: "/Block-After-Grace-Period",
            name: "KYC Block After Grace Period",
            functionalCode: "DOCUMENT_UPLOAD",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: KycBlockAfterGrace,
          },
        ],
      },
    ],
  },
  {
    name: "Wallet Operation",
    functionalName: "",
    path: "",
    isLevelTwo: true,
    subMenu: true,
    sidebar: true,
    key: "walletOperation",
    layout: "/dashboard",
    menuItems: [
      {
        name: "Merchant Summary",
        functionalCode: "REMITTANCE_BO_SETUP",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "walletMerchant",
        additionalMenuItems: [
          {
            path: "/MerchantSummaryHQ",
            name: "Merchant Summary HQ",
            functionalCode: "MERCHANT_SUMMARY",
            L2functionalName: "Payout Country",
            visibleInMenu: true,
            key: "/dashboard/MerchantSummaryHQ",
            layout: "/dashboard/MerchantSummaryHQ",
            component: MerchantSummaryHq,
          },
          {
            path: "/MerchantSummaryHQ/Add",
            name: "Add Merchant",
            functionalCode: "MERCHANT_SUMMARY",
            visibleInMenu: false,
            key: "/dashboard",
            layout: "/dashboard",
            component: MerchantSummaryAdd,
          },
          {
            path: "/MerchantSummaryHQ/view",
            name: "View Merchant Summary",
            functionalCode: "MERCHANT_SUMMARY",
            visibleInMenu: false,
            key: "/dashboard",
            layout: "/dashboard",
            component: MerchantSummaryView,
          },
          {
            path: "/MerchantSummaryHQ/Edit",
            name: "Edit Merchant Summary",
            functionalCode: "MERCHANT_SUMMARY",
            visibleInMenu: false,
            key: "/dashboard",
            layout: "/dashboard",
            component: MerchantSummaryHQEdit,
          },
          {
            path: "/MerchantBranch",
            name: "Merchant Branch",
            functionalCode: "PAYOUT_COUNTRY",
            L2functionalName: "Payout Country",
            visibleInMenu: true,
            key: "/dashboard/MerchantBranch",
            layout: "/dashboard/MerchantBranch",
            // component: MerchantBranch,
          },
        ],
      },
    ],
  },
  {
    name: "Reports",
    functionalName: "",
    path: "",
    isLevelTwo: true,
    subMenu: true,
    sidebar: true,
    key: "sub9",
    layout: "/dashboard",
    menuItems: [
      {
        name: "noSubmenu",
        functionalCode: "SRF",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "reports",
        additionalMenuItems: [
          {
            path: "/IdExpiring-Reports",
            name: "ID Expiring Reports",
            functionalCode: "ID_EXPIRY_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/SRF",
            layout: "/dashboard/SRF",
            component: IdExpiringReports,
          },
        ],
      },

      {
        name: "Card Block",
        functionalCode: "SRF",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "reportsBlock",
        additionalMenuItems: [
          {
            path: "/SRFBlockCard",
            name: "SRF Block Card ",
            functionalCode: "SRF_CARD_BLOCK_PENDING_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/SRFBlockCard",
            layout: "/dashboard/SRF",
            component: BlockCardPending,
          },
        ],
      },
      {
        name: "Card UnBlock",
        functionalCode: "SRF",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "reportsUnblock",
        additionalMenuItems: [
          {
            path: "/SRFUnBlockCard",
            name: "SRF UnBlock Card",
            functionalCode: "SRF_CARD_UNBLOCK_PENDING_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/SRFUnBlockCard",
            layout: "/dashboard/SRF",
            component: UnblockCardPending,
          },
        ],
      },
      {
        name: "Document Update Report",
        functionalCode: "SRF",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "reportsUpdate",
        additionalMenuItems: [
          {
            path: "/KYCUpdateCard",
            name: "SRF Document Update",
            functionalCode: "SRF_CARD_KYC_UPDATE_PENDING_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/KYCUpdateCard",
            layout: "/dashboard/SRF",
            component: KYCUpdatePending,
          },
        ],
      },
      {
        name: "Wallet Upgrade Report ",
        functionalCode: "SRF",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "reportsWallet",
        additionalMenuItems: [
          {
            path: "/WalletUpgrade",
            name: "Wallet Upgrade Report",
            functionalCode: "SRF_CARD_WALLET_UPGRADE_PENDING_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/WalletUpgrade",
            layout: "/dashboard/SRF",
            component: WalletPending,
          },
        ],
      },
      {
        name: "Remittance Transaction Report",
        functionalCode: "SRF",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "remittanceTransaction",
        additionalMenuItems: [
          {
            path: "/DailyTransactionReport",
            name: "Daily Transaction Report",
            functionalCode: "DAILY_TRANSACTION_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/DailyTransactionReport",
            layout: "/dashboard",
            component: DailyTransactionReport,
          },
          {
            path: "/MonthlyTransactionReport",
            name: "Monthly Transaction Report",
            functionalCode: "MONTHLY TRANSACTION_REPORT",
            L2functionName: "",
            visibleInMenu: true,
            key: "/dashboard/MonthlyTransactionReport",
            layout: "/dashboard",
            component: MonthlyTransactionReport,
          },
          {
            path: "/RefundTransactionReport",
            name: "Refund Transaction Report",
            functionalCode: "REFUND_TRANSACTION_REPORT",
            L2functionName: "",
            visibleInMenu: true,
            key: "/dashboard/RefundTransactionReport",
            layout: "/dashboard",
            component: RefundTransactionReport,
          },
          {
            path: "/OnBehalfSenderReport",
            name: "On Behalf Of Sender Report",
            functionalCode: "ON_BEHALF_SENDER_REPORT",
            L2functionName: "",
            visibleInMenu: true,
            key: "/dashboard/OnBehalfSenderReport",
            layout: "/dashboard",
            component: OnBehalfSenderReport,
          },
          {
            path: "/MIRS-Declined-Transaction-Report",
            name: "MIRS Declined Transaction Report",
            functionalCode: "MIRS_DECLINED_TRANSACTION_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/remittanceTransactionReport",
            layout: "/dashboard/remittanceTransactionReport",
            component: MIRSDeclinedTransactionReport,
          },
          {
            path: "/RejectedTransactionReport",
            name: "Rejected Transaction Report",
            functionalCode: "REJECTED_TRANSACTION_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/remittanceTransactionReport",
            layout: "/dashboard/remittanceTransactionReport",
            component: RejectedTransactionReport,
          },
          {
            path: "/transaction-report",
            name: "Transaction Summary Report",
            functionalCode: "TRANSACTION_SUMMARY_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/transaction-report",
            layout: "/dashboard",
            component: TransactionSummaryReport,
          },
          {
            path: "/FailedTransactionReport",
            name: "Failed Transaction Report",
            functionalCode: "FAILED_TRANSACTION_REPORT",
            L2functionName: "",
            visibleInMenu: true,
            key: "/dashboard/FailedTransactionReport",
            layout: "/dashboard",
            component: FailedTxnReport,
          },
          {
            path: "/end-of-day-report",
            name: "End of Day Report",
            functionalCode: "END_OF_DAY_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/end-of-day-report",
            layout: "/dashboard",
            component: EndofDayReport,
          },
          {
            path: "/AvgDailyMonthlyTxnComparsionReport",
            name: "Average Monthly Transaction Report",
            functionalCode: "AVG_TRANSACTION_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/AvgDailyMonthlyTxnComparsionReport",
            layout: "/dashboard",
            component: AvgDailyMonthlyTransactionReport,
          },
        ],
      },

      {
        name: "Security Report",
        functionalCode: "SRF",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "securityReport",
        additionalMenuItems: [
          {
            path: "/UAMreport",
            name: "UAM Report",
            functionalCode: "UAM_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/UAMreport",
            layout: "/dashboard",
            component: UAMreport,
          },
          {
            path: "/BranchManagementReport",
            name: "Branch Management Report",
            functionalCode: "BRANCH_MANAGEMENT_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/BranchManagementreport",
            layout: "/dashboard",
            component: BranchManagementReport,
          },
          {
            path: "/CustomerLoginReport",
            name: "Customer Login Report",
            functionalCode: "CUSTOMER_LOGIN_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/CustomerLoginReport",
            layout: "/dashboard",
            component: CustomerLoginReport,
          },
          {
            path: "/SmsTransactionReport",
            name: "SMS Transaction Report",
            functionalCode: "SMS_TRANSACTION_REPORT",
            L2functionName: "",
            visibleInMenu: true,
            key: "/dashboard/SmsTransactionReport",
            layout: "/dashboard",
            component: SmsTransactionReport,
          },
        ],
      },
      {
        name: "AML Compliance Reports",
        functionalCode: "SRF",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "AMLCompilanceReports",
        additionalMenuItems: [
          {
            path: "/AMLCFTReports",
            name: "AMLCFT Reports",

            functionalCode: "AMLCFT_REPORTS",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/AMLCFTreports",
            layout: "/dashboard",
            component: AMLCFTReports,
          },
          {
            path: "/CustomerRiskProfilingReport",
            name: "Customer Risk Profiling Reports",
            functionalCode: "CUSTOMER_RISK_PROFILING_REPORTS",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/CustomerRiskProfilingReport",
            layout: "/dashboard",
            component: CustomerRiskProfilingReport,
          },
          {
            path: "/ECDDReport",
            name: "ECDD Report",
            functionalCode: "ECDD_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/ECDDReport",
            layout: "/dashboard",
            component: ECDDReport,
          },
          {
            path: "/CustomerRiskSummaryReport",
            name: "Customer Risk Summary Report",
            functionalCode: "CUSTOMER_RISK_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/CustomerRiskSummaryReport",
            layout: "/dashboard",
            component: CustomerRiskSummaryReport,
          },
          {
            path: "/TransactionReport",
            name: "Transaction Screening Report",
            functionalCode: "TRANSACTION_SCREENING_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/TransactionReport",
            layout: "/dashboard",
            component: TransactionReport,
          },
          {
            path: "/TransactionSummaryReport",
            name: "Transaction Summary Report",
            functionalCode: "TRANSACTION_SUMMARY_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/TransactionSummaryReport",
            layout: "/dashboard",
            component: AMLTransactionSummaryReport,
          },
        ],
      },
      {
        name: "Onboarding Report",
        functionalCode: "ONBOARDING_REPORTS",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "OnboardingReport",
        additionalMenuItems: [
          {
            path: "/OnBoardingSummaryReport",
            name: "Onboarding Summary Report",
            functionalCode: "ONBOARDING_SUMMARY_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/OnBoardingSummaryReport",
            layout: "/dashboard",
            component: OnBoardingSummaryReport,
          },
          {
            path: "/OnBoardingDetailReport",
            name: "Onboarding Detail Report",
            functionalCode: "ONBOARDING_DETAIL_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/OnBoardingDetailReport",
            layout: "/dashboard",
            component: OnBoardingDetailsReport,
          },
          {
            path: "/MSSLTrackerListReport",
            name: "MSSLTracker List Report",
            functionalCode: "ONBOARDING_MSSLTRACKER_LIST_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/MSSLTrackerListReport",
            layout: "/dashboard",
            component: MSSLTrackerListReport,
          },
          {
            path: "/MaintenanceListReport",
            name: "Maintenance List Report",
            functionalCode: "ONBOARDING_MAINTENANCE_LIST_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/MaintenanceListReport",
            layout: "/dashboard",
            component: MaintenanceListReport,
          },
          {
            path: "/GroupNameSummaryReport",
            name: "Group Name Summary Report",
            functionalCode: "ONBOARDING_GROUPNAME_SUMMARY_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/GroupNameSummaryReport",
            layout: "/dashboard",
            component: GroupNameSummaryReport,
          },
          {
            path: "/CustomerScreeningReport",
            name: "Customer Screening Report",
            functionalCode: "AML_PNDG_CUST",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/CustomerScreeningReport",
            layout: "/dashboard",
            component: CustomerscreenReport,
          },
          {
            path: "/MarketingReport",
            name: "Marketing Report",
            functionalCode: "MARKETING_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/MarketingReport",
            layout: "/dashboard",
            component: MarketingReport,
          },
          {
            path: "/salesReport",
            name: "Sales Report",
            functionalCode: "AML_PNDG_CUST",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/salesReport",
            layout: "/dashboard",
            component: Salesreport,
          },
        ],
      },
      {
        name: "Payroll Reports",
        functionalCode: "",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "PayrollReport",
        additionalMenuItems: [
          {
            path: "/PayrollCompanyCreation",
            name: "Payroll Company Creation",
            functionalCode: "PAYROLL_COMPANY_CREATION_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/PayrollCompanyCreation",
            layout: "/dashboard",
            component: PayrollCompanyCreation,
          },
          {
            path: "/TopupReconciliationReport",
            name: "Topup Reconciliation Report",
            functionalCode: "TOPUP_RECONCILIATION_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/TopupReconciliationReport",
            layout: "/dashboard",
            component: TopupReconciliationReport,
          },
          {
            path: "/PrefundReconciliationReport",
            name: "Prefund Reconciliation Report",
            functionalCode: "PREFUND_RECONCILIATION_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/PrefundReconciliationReport",
            layout: "/dashboard",
            component: PrefundReconciliationReports,
          },
          {
            path: "/PayrollSummaryReport",
            name: "Payroll Transaction Summary Report",
            functionalCode: "PAYROLL_TXN_SUMARY_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/PayrollSummaryReport",
            layout: "/dashboard",
            component: PayrollSummaryReport,
          },
          {
            path: "/PayrollDetailReport",
            name: "Payroll Transaction Detail Report​",
            functionalCode: "PAYROLL_TXN_DETAIL_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/PayrollDetailReport",
            layout: "/dashboard",
            component: PayrollDetailReport,
          },
          {
            path: "/PrefundAmountReport",
            name: "Prefund Amount Report​",
            functionalCode: "PREFUND_AMOUNT_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/PrefundAmountReport",
            layout: "/dashboard",
            component: PrefundAmountReport,
          },
          {
            path: "/PrefundDebitReport​",
            name: "Prefund Debit Report​​",
            functionalCode: "PREFUND_DEBIT_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/PrefundDebitReport​",
            layout: "/dashboard",
            component: PrefundDebitReport,
          },
          {
            path: "/PrefundCreditReport​",
            name: "Prefund Credit Report​​",
            functionalCode: "PREFUND_CREDIT_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/PrefundCreditReport​",
            layout: "/dashboard",
            component: PrefundCreditReport,
          },
          {
            path: "/PrefundBalanceByCompany",
            name: "Prefund Balance By Company",
            functionalCode: "PAYROLL_PREFUND_BALANCE_COMPANY_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/PrefundBalanceByCompany",
            layout: "/dashboard",
            component: PrefundBalanceByCompany,
          },
          {
            path: "/PayrollTxnByCompany",
            name: "Payroll Transaction By Company",
            functionalCode: "PAYROLL_TXN_BY_COMPANY_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/PayrollTxnByCompany",
            layout: "/dashboard",
            component: PayrollTxnByCompany,
          },
          {
            path: "/TransactionHistoryReport",
            name: "Transaction History Report",
            functionalCode: "TRANSACTION_HISTORY_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/TransactionHistoryReport",
            layout: "/dashboard",
            component: TransactionHistoryReport,
          },
        ],
      },
      {
        name: "Life Cycle Reports",
        functionalCode: "",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "LifeCycleReport",
        additionalMenuItems: [
          {
            path: "/walletDowngradeReport",
            name: "Wallet Downgrade Report",
            functionalCode: "AML_PNDG_CUST",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/walletDowngradeReport",
            layout: "/dashboard",
            component: WalletDowngradeReport,
          },
          {
            path: "/topUpCommonReport",
            name: "TopUp Common Report ",
            functionalCode: "TOP_UP_COMMON_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/topUpCommonReport",
            layout: "/dashboard",
            component: TopUpCommonReport,
          },
        ],
      },
      {
        name: "noSubmenu",
        functionalCode: "SRF",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "reports",
        additionalMenuItems: [
          {
            path: "/auditTrialReport",
            name: "Audit Trail Report",
            functionalCode: "AUDIT_TRAIL_REPORT",
            L2functionalName: "",
            visibleInMenu: true,
            key: "/dashboard/SRF",
            layout: "/dashboard",
            component: AuditTrialReport,
          },
        ],
      },
    ],
  },
  {
    name: "Valyou",
    functionalName: "",
    path: "",
    isLevelTwo: true,
    subMenu: true,
    sidebar: true,
    key: "valyou",
    layout: "/dashboard",
    menuItems: [
      {
        name: "Merchant Setup",
        functionalCode: "Merchant_setup",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "valyoumerchant",
        additionalMenuItems: [
          {
            path: "/Merchant-Setup",
            name: "Merchant Setup",
            functionalCode: "Merchant_setup",
            L2functionalName: "KYC",
            visibleInMenu: true,
            key: "/dashboard/Merchant-Setup",
            layout: "/dashboard",
            component: Merchantsetup,
          },
          {
            path: "/Merchant-Branch-Summary",
            name: "Merchant Branch Summary",
            functionalCode: "Merchant_setup",
            L2functionalName: "KYC",
            visibleInMenu: true,
            key: "/dashboard/Merchant-Branch-Summary",
            layout: "/dashboard",
            component: MerchantBranchSummary,
          },
          {
            path: "/Merchant-Teller-Summary",
            name: "Merchant Teller Summary",
            functionalCode: "Merchant_setup",
            L2functionalName: "KYC",
            visibleInMenu: true,
            key: "/dashboard/Merchant-Teller-Summary",
            layout: "/dashboard",
            component: MerchantTellerSummary,
          },
        ],
      },
    ],
  },
  {
    name: "Others",
    functionalName: "",
    path: "",
    isLevelTwo: true,
    subMenu: true,
    sidebar: true,
    key: "sub_5",
    layout: "/dashboard",
    menuItems: [
      {
        name: "noSubmenu",
        functionalCode: "TEST",
        L1functionalName: "",
        secondSubmenu: true,
        visibleInMenu: true,
        layout: "/dashboard",
        key: "BOSetup_5",
        additionalMenuItems: [
          {
            path: "/eKYC-Pending-Customer",
            name: "eKYC Pending Customer",
            functionalCode: "PENDING_ONBOARDING",
            L2functionalName: "eKYC Pending Customer",
            visibleInMenu: false,
            key: "/dashboard/eKYC-Pending-Customer",
            layout: "/dashboard",
            component: eKYCPendingCustomer,
          },
          {
            path: "/KYC-Customer",
            name: "Pending Onboarding",
            functionalCode: "KYC_Customer_Profile",
            L2functionalName: "KYC",
            visibleInMenu: true,
            key: "/dashboard/KYC-Customer",
            layout: "/dashboard",
            component: KYCPendingCustomer,
          },
          {
            path: "/KYC-Customer-Enquiry",
            name: "Customer Enquiry",
            functionalCode: "CUST_ENQUIRY",
            L2functionalName: "KYC",
            visibleInMenu: true,
            key: "/dashboard/KYC-Customer-Enquiry",
            layout: "/dashboard",
            component: KYCCustomerEnquiry,
          },
          {
            path: "/Pending-AML-Customers",
            name: "Pending AML Customers",
            functionalCode: "AML_PNDG_CUST",
            L2functionalName: "Pending AML Customers",
            visibleInMenu: true,
            key: "/dashboard/Pending-AML-Customers",
            layout: "/dashboard",
            component: AmlPendingCustomers,
          },
          {
            path: "/bank-Payment-Gateway-Mapping",
            name: "FPX Bank Setup",
            functionalCode: "FPX_BANK_SETUP",
            L2functionalName: "Bank Payment Gateway Mapping",
            visibleInMenu: true,
            key: "/dashboard/bank-Payment-Gateway-Mapping",
            layout: "/dashboard",
            component: BankPaymentGatewayMapping,
          },
          {
            path: "/Toggle-Summary",
            name: "Toggle Summary",
            functionalCode: "TOGGLE_SUMMARY",
            L2functionalName: "Toggle Summary",
            visibleInMenu: true,
            key: "/dashboard/Toggle-Summary",
            layout: "/dashboard",
            component: ToggleSummary,
          },
          {
            path: "/parameter-summary",
            name: "Parameter Summary",
            functionalCode: "PARAMETER_SUMMARY",
            L2functionalName: "Parameter Summary",
            visibleInMenu: true,
            key: "/dashboard/parameter-summary",
            layout: "/dashboard",
            component: ParameterSummary,
          },
          {
            path: "/edit-summary-notification",
            name: "Edit Summary",
            functionalCode: "EDIT_SUMMARY_NOTIFICATION",
            L2functionalName: "Edit Summary",
            visibleInMenu: false,
            key: "/dashboard/edit-summary-notification",
            layout: "/dashboard",
            component: CommonEditSummary,
          },
          {
            path: "/edit-summary-parameter",
            name: "Edit Summary",
            functionalCode: "NOTIFICATION_SUMMARY",
            L2functionalName: "Edit Summary Parameter",
            visibleInMenu: false,
            key: "/dashboard/edit-summary-parameter",
            layout: "/dashboard",
            component: CommonEditSummary,
          },
          {
            path: "/AMLcompliance-config",
            name: "AMLcompliance Config",
            functionalCode: "AML_COMP_CONFIG",
            L2functionalName: "AMLcompliance Config",
            visibleInMenu: true,
            key: "/dashboard/AMLcompliance-config",
            layout: "/dashboard",
            component: AMLcompliance,
          },
          {
            path: "/Mobile-TopUp-Summary-DashBoard",
            name: "Mobile TopUp Summary",
            functionalCode: "MOBILE_TOPUP_SUMMARY",
            L2functionalName: "Mobile TopUp Summary",
            visibleInMenu: true,
            key: "/dashboard/Mobile-TopUp-Summary-DashBoard",
            layout: "/dashboard",
            component: MobileTopUpSummary,
          },
          {
            path: "/Mobile-TopUp-Summary",
            name: "Mobile TopUp Summary",
            functionalCode: "KYC_Customer_Profile",
            L2functionalName: "Mobile TopUp Summary",
            visibleInMenu: false,
            key: "/dashboard/Mobile-TopUp-Summary",
            layout: "/dashboard",
            component: MobileTopupSummaryTable,
          },
          {
            path: "/OTP-List",
            name: "OTP List",
            functionalCode: "TEST_OTP_DASHBOARD",
            L2functionalName: "OTP",
            visibleInMenu: true,
            key: "/dashboard/OTP-List",
            layout: "/dashboard",
            component: OTPTempTable,
          },
          {
            path: "/valyou/vedioCall",
            name: "Valyou SRHCT POC",
            functionalCode: "TEST_OTP_DASHBOARD",
            L2functionalName: "Valyou SRHCT POC",
            visibleInMenu: true,
            key: "/dashboard/valyou/vedioCall",
            layout: "/dashboard",
            component: ValyouSRHCT,
          },
          {
            path: "/Account-Summary",
            name: "Account Summary",
            functionalCode: "TEST_OTP_DASHBOARD",
            L2functionalName: "Account",
            visibleInMenu: true,
            key: "/dashboard/Account-Summary",
            layout: "/dashboard",
            component: AccountSummary,
          },
        ],
      },
    ],
  },
];

export default functionalCodeRoutes;
