export const Customer = {
    "countryCode" : "MY",
    "entityId": "92af85f3-bc0f-4831-bf6d-956bb9402774",
    "entityCode" : "MTAMY",
    "customerName" : "",
    "preferredName" : "",
    "mobileNumber" : "",
    "nationalityCode" : "M",
    "idTypeCode" : "IC",
    "idValue" : "",
    "birthDate" : "",
   "emailAddress" : "",
    "mothersMaidenName": "",
    "residentAddress1": "",
    "residentAddress2" : "",
    "residentPostcode" : "",
    "residentCityCode" : "",
    "residentCityDescription" : "",
    "residentStateCode" : "",
    "residentStateDescription" : "",
    "residentCountryCode" : "aaaa",
    "residentCountryDescription" : "aaa",
    "isSameAddress" : "",
    "mailAddress1" : "",
    "mailAddress2" :  "",
    "mailPostcode" : "",
    "mailCityCode" : "",
    "mailCityDescription" : "",
    "mailStateCode" : "",
    "mailStateDescription" : "",
   "mailCountryCode" : "",
    "mailCountryDescription" : "",
    "occupation" : "",
   "preferredLanguage" : "",
    "linkEmployer" : "",
    "bankName" : "",
    "bankAccountNo" : "",
    "onboardingChannel" : "",
    "remarks" : "",
    
   

}